#!/bin/zsh
#
# func/rtest
#
# Run a bunch of ruby test cases. Accepts multiple files and/or folders.
# Uses spring if it's available.

if [[ -n "$(whence -p spring)" && (-f "config/application.rb" || -f "config/spring.rb" ) && -z $NOSPRING ]]; then
  command spring spec $*
else
  bundle exec ruby -I'.:spec:spec/support' -e 'args = ARGV.dup
    finish = (( e = args.find {|e| e[/^-/] } )) && args.index(e) || 0
    requires = args[0..finish - 1]
    args -= requires
    $0 = "rtest #{requires.join(", ")} #{args.join(" ")}"
    requires.map do |path|
      path = File.expand_path(path)
      File.directory?(path) ? Dir[File.join(path, "**/*_spec.rb")].to_a : path
    end.flatten.each {|file| require file }' $*
fi
