#!/bin/zsh
setopt extendedglob

cd $HOME/.dotfiles/profiles/harry

function command_exists() {
  command -v "$@" > /dev/null 2>&1
}

if command_exists "brew"; then
  brew bundle --file=../dev/Brewfile
  brew bundle --file=Brewfile
fi
