source_files_in_directory() {
  local dir="$1"
  echo "Loading files in ${dir}..."

  if [[ -d "$dir" ]]; then
    for file in ${(o)dir}/*(N); do
      if [[ -f $file ]]; then
        source "$file"
      fi
    done
  else
    echo "Directory '$dir' does not exist."
  fi
}

source_files_in_directory $ZDOTDIR/zshenv.d

export TZ=/usr/share/zoneinfo/America/Toronto
export GPG_TTY=$(tty)
export PAGER="less -X"
export MANPAGER="less -X"
