source_files_in_directory() {
  local dir="$1"
  if [[ -d "$dir" ]]; then
    for file in ${(o)dir}/*(N); do
      [[ -f $file ]] && source "$file"
    done
  fi
}

# Load our ZSH config if we're not running in Cursor
if [[ -z "$CURSOR_AGENT" ]]; then
  source_files_in_directory $ZDOTDIR/zshenv.d
fi

export TZ=/usr/share/zoneinfo/America/Toronto
export GPG_TTY=$(tty)
export PAGER="less -X"
export MANPAGER="less -X"
