source_files_in_directory() {
  local dir="$1"

  if [[ -d "$dir" ]]; then
    for file in ${(o)dir}/*(N); do
      if [[ -f $file ]]; then
        source "$file"
      fi
    done
  else
    echo "Directory '$dir' does not exist."
  fi
}

source_files_in_directory $ZDOTDIR/zshrc.d

[ -f ~/.zsh/zshrc.local ] && source ~/.zsh/zshrc.local
